version: '3.1'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker # User: root
    ports:
     - 3306:3306
volumes:
  db-data:
networks:
  default:
    external:
      name: ga-tech

# CLI Access:
# docker-compose run --rm mysql-server mysql -h mysql-server -u root -p